"use client";

import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Github, Linkedin, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";

import Link from "next/link";

export default function About() {
  return (
    <section id="about" className="space-y-6 scroll-mt-20">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        viewport={{ once: true }}
      >
        <Card className="p-4 backdrop-blur-sm bg-card/50 space-y-4">
          <div className="space-y-2">
            <h2 className="text-heading-1 font-bold">About Me</h2>
            <p className="text-muted-foreground leading-relaxed text-paragraph">
              Hi there! I’m Dharmick. I am deeply passionate about data. I
              combine advanced technical skills with a strong understanding of
              business challenges to develop solutions that drive tangible
              results. My love for technology stems from a lifelong fascination
              with building things and solving problems, all while fostering
              connections with people and embracing an entrepreneurial mindset.
            </p>
            <p className="text-muted-foreground leading-relaxed text-paragraph">
              This passion has shaped my diverse career journey. After earning a
              BSc in Physics from Victoria University of Wellington, I
              co-founded One Earth Technologies (now Special Studios), a 3D
              printing business focused on eco-friendly solutions. Concurrently,
              I worked as a data and strategy analyst in New Zealand's renewable
              energy sector, where I developed a profound appreciation for
              sustainable energy initiatives.
            </p>
            <p className="text-muted-foreground leading-relaxed text-paragraph">
              In 2023, I relocated from Tauranga, NZ, to Melbourne, Australia,
              to join Mecca Brands as a Reporting and Insights Analyst. At
              Mecca, I developed a SARIMAX forecasting model to measure the
              incremental revenue generated by marketing campaigns—an
              achievement I had the privilege of presenting to the CEO on
              multiple occasions.
            </p>
            <p className="text-muted-foreground leading-relaxed text-paragraph">
              <span className="font-semibold text-foreground">
                Currently based in Melbourne, Australia
              </span>
            </p>
            <div className="pt-4 flex flex-wrap gap-2">
              <Badge variant="secondary">Data Science</Badge>
              <Badge variant="secondary">Machine Learning</Badge>
              <Badge variant="secondary">Strategy</Badge>
              <Badge variant="secondary">Analytics</Badge>
            </div>
            <div className="pt-4 flex gap-2">
              <Button variant="outline" size="icon" asChild>
                <Link
                  href="https://github.com/DharmickM"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-name-accent transition-colors duration-200"
                >
                  <Github className="h-4 w-4" />
                </Link>
              </Button>
              <Button variant="outline" size="icon" asChild>
                <Link
                  href="https://www.linkedin.com/in/DharmM/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-name-accent transition-colors duration-200"
                >
                  <Linkedin className="h-4 w-4" />
                </Link>
              </Button>
              <Button variant="outline" size="icon" asChild>
                <Link
                  href="mailto:dharmick95@gmail.com"
                  className="hover:text-name-accent transition-colors duration-200"
                >
                  <Mail className="h-4 w-4" />
                </Link>
              </Button>
            </div>
          </div>
        </Card>
      </motion.div>
    </section>
  );
}
